// Generated by CoffeeScript 1.9.3
(function() {
  var dest_path, flatten, gulp, gulpFilter, mainBowerFiles, minifycss, rename, uglify;

  gulp = require('gulp');

  flatten = require('gulp-flatten');

  gulpFilter = require('gulp-filter');

  uglify = require('gulp-uglify');

  minifycss = require('gulp-minify-css');

  rename = require('gulp-rename');

  mainBowerFiles = require('main-bower-files');

  dest_path = 'build';

  gulp.task('bower', function() {
    var cssFilter, fontFilter, jsFilter;
    jsFilter = gulpFilter('*.js');
    cssFilter = gulpFilter('*.css');
    fontFilter = gulpFilter(['*.eot', '*.woff', '*.svg', '*.ttf']);
    gulp.src(mainBowerFiles()).pipe(jsFilter).pipe(gulp.dest(dest_path + '/js/')).pipe(uglify()).pipe(rename({
      suffix: '.min'
    })).pipe(gulp.dest(dest_path + '/js/'));
    return gulp.src(mainBowerFiles()).pipe(fontFilter).pipe(flatten()).pipe(gulp.dest(dest_path + '/fonts'));
  });

}).call(this);

//# sourceMappingURL=bower.js.map
