// Generated by CoffeeScript 1.9.3
(function() {
  var browserSync, gulp, reload;

  gulp = require('gulp');

  browserSync = require('browser-sync');

  reload = browserSync.reload;

  gulp.task('fonts', function() {
    return gulp.src("./app/fonts/{'*.eot','*.woff','*.svg','*.ttf'}").pipe(gulp.dest('./build')).pipe(reload({
      stream: true
    }));
  });

}).call(this);

//# sourceMappingURL=fonts.js.map
