// Generated by CoffeeScript 1.9.3
(function() {
  var browserSync, concat, gulp, reload;

  gulp = require('gulp');

  concat = require('gulp-concat');

  browserSync = require('browser-sync');

  reload = browserSync.reload;

  gulp.task('clientscripts', function() {
    return gulp.src('app/js/*.js').pipe(concat('main.js')).pipe(gulp.dest('build/js')).pipe(reload({
      stream: true
    }));
  });

}).call(this);

//# sourceMappingURL=scripts.js.map
