// Generated by CoffeeScript 1.9.3
(function() {
  var app;

  app = angular.module('fixApp', ['ngRoute']);

  app.config([
    "$routeProvider", function($routeProvider) {
      return $routeProvider.when("/login", {
        templateUrl: "partials/login.html",
        controller: 'loginCtrl',
        controllerAs: 'login'
      }).when("/calc", {
        templateUrl: "partials/calc.html",
        controller: 'calcCtrl',
        controllerAs: 'calc'
      }).otherwise({
        redirectTo: "/login"
      });
    }
  ]).run(function($rootScope, $location) {
    return $rootScope.$on('$routeChangeStart', function(event, next) {
      if ($rootScope.loggedUser === null) {
        if (next.templateUrl !== "partials/login.html") {
          return $location.path("/login");
        }
      }
    });
  });

  app.controller("loginCtrl", [
    '$scope', '$location', '$rootScope', function($scope, $location, $rootScope) {
      $scope.email = "admin@admin.ru";
      $scope.pass = "asdf";
      $scope.submit = function() {
        $rootScope.loggedUser = "admin";
        $location.path("/calc");
      };
    }
  ]);

  app.controller("calcCtrl", ['$scope', '$location', '$rootScope', function($scope, $location, $rootScope) {}]);

}).call(this);

//# sourceMappingURL=main.js.map
