// Generated by CoffeeScript 1.9.3
(function() {
  var app, calcCtrl, loginCtrl;

  app = angular.module("fixApp", ["ngRoute"]);

  app.config([
    "$routeProvider", function($routeProvider) {
      return $routeProvider.when("/login", {
        templateUrl: "partials/login.html",
        controller: loginCtrl
      }).otherwise({
        redirectTo: "/login"
      });
    }
  ]);

  app.controller("loginCtrl", loginCtrl = (function() {
    function loginCtrl() {}

    return loginCtrl;

  })());

  app.controller("calcCtrl", calcCtrl = (function() {
    function calcCtrl() {}

    return calcCtrl;

  })());

  angular.bootstrap(document, ["fixApp"]);

}).call(this);

//# sourceMappingURL=main.js.map
